#pragma once
// Autoresearch tunable parameters for gpu_csv_parser.cu
// This file is auto-generated by the experiment script.

#define TUNE_THREADS_PER_BLOCK 256
#define TUNE_MARK_THREADS_PER_BLOCK 256
#define TUNE_COMPACT_THREADS_PER_BLOCK 256
#define TUNE_USE_WARP_PARSE 1
#define TUNE_USE_FAST_PARSER 1
#define TUNE_MAX_FIELDS_PER_WARP 32
#define TUNE_USE_WIDE_LOADS 0
#define TUNE_NUM_STREAMS 1
#define TUNE_MIN_CHUNK_SIZE_BYTES (32 * 1024 * 1024)
